from __future__ import annotations

import csv
from datetime import datetime, timezone
import json
from pathlib import Path
from typing import Any


MAPPING_FIELDNAMES = [
    "canonical_ticker",
    "niche",
    "execution_phase",
    "market_description",
    "settlement_source",
    "settlement_source_url",
    "release_time_et",
    "schedule_source_url",
    "schedule_needs_nightly_poll",
    "schedule_holiday_shift_risk",
    "source_timestamp_rule",
    "mispricing_hypothesis",
    "confounders",
    "mapping_status",
    "live_event_ticker",
    "live_market_ticker",
    "mapping_confidence",
    "mapping_notes",
    "last_mapped_at",
]

THRESHOLD_FIELDNAMES = [
    "canonical_ticker",
    "niche",
    "execution_phase",
    "release_cluster",
    "entry_min_edge_net",
    "entry_min_confidence",
    "entry_min_evidence_count",
    "entry_max_price_dollars",
    "entry_max_spread_dollars",
    "per_market_risk_cap_fraction_nav",
    "release_cluster_risk_cap_fraction_nav",
    "same_day_correlated_risk_cap_fraction_nav",
    "daily_soft_stop_fraction_nav",
    "daily_hard_stop_fraction_nav",
    "drawdown_soft_cap_fraction_nav",
    "drawdown_hard_kill_fraction_nav",
    "degrade_to_paper_after_stopouts",
    "stopout_window_sessions",
    "target_outperformance_vs_spx_points_min",
    "target_outperformance_vs_spx_points_max",
    "notes",
]

EDITABLE_MAPPING_FIELDS = (
    "mapping_status",
    "live_event_ticker",
    "live_market_ticker",
    "mapping_confidence",
    "mapping_notes",
    "last_mapped_at",
)


def _read_csv_rows(path: Path) -> list[dict[str, str]]:
    if not path.exists():
        return []
    with path.open("r", newline="", encoding="utf-8") as handle:
        return [dict(row) for row in csv.DictReader(handle)]


def _write_csv(path: Path, fieldnames: list[str], rows: list[dict[str, Any]]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with path.open("w", newline="", encoding="utf-8") as handle:
        writer = csv.DictWriter(handle, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)


def _spec(
    *,
    canonical_ticker: str,
    niche: str,
    execution_phase: str,
    release_cluster: str,
    market_description: str,
    settlement_source: str,
    settlement_source_url: str,
    release_time_et: str,
    schedule_source_url: str,
    schedule_needs_nightly_poll: bool,
    schedule_holiday_shift_risk: bool,
    source_timestamp_rule: str,
    mispricing_hypothesis: str,
    confounders: str,
    entry_min_edge_net: float,
    entry_min_confidence: float,
    entry_min_evidence_count: int,
    entry_max_price_dollars: float,
    entry_max_spread_dollars: float,
    per_market_risk_cap_fraction_nav: float,
    notes: str,
) -> dict[str, Any]:
    return {
        "canonical_ticker": canonical_ticker,
        "niche": niche,
        "execution_phase": execution_phase,
        "release_cluster": release_cluster,
        "market_description": market_description,
        "settlement_source": settlement_source,
        "settlement_source_url": settlement_source_url,
        "release_time_et": release_time_et,
        "schedule_source_url": schedule_source_url,
        "schedule_needs_nightly_poll": schedule_needs_nightly_poll,
        "schedule_holiday_shift_risk": schedule_holiday_shift_risk,
        "source_timestamp_rule": source_timestamp_rule,
        "mispricing_hypothesis": mispricing_hypothesis,
        "confounders": confounders,
        "entry_min_edge_net": entry_min_edge_net,
        "entry_min_confidence": entry_min_confidence,
        "entry_min_evidence_count": entry_min_evidence_count,
        "entry_max_price_dollars": entry_max_price_dollars,
        "entry_max_spread_dollars": entry_max_spread_dollars,
        "per_market_risk_cap_fraction_nav": per_market_risk_cap_fraction_nav,
        "notes": notes,
    }


def _macro_specs() -> list[dict[str, Any]]:
    bls_url = "https://www.bls.gov/schedule/news_release/current_year.asp"
    census_url = "https://www.census.gov/economic-indicators/calendar-listview.html"
    bea_url = "https://www.bea.gov/news/schedule"
    fed_url = "https://www.federalreserve.gov/newsevents/calendar.htm"

    macro_common = {
        "niche": "macro_release",
        "execution_phase": "phase1_live",
        "entry_min_edge_net": 0.012,
        "entry_min_confidence": 0.58,
        "entry_min_evidence_count": 3,
        "entry_max_price_dollars": 0.72,
        "entry_max_spread_dollars": 0.05,
        "per_market_risk_cap_fraction_nav": 0.003,
        "notes": "Macro release contract; do not hardcode release date, poll schedule nightly.",
    }

    return [
        _spec(
            canonical_ticker="MX01_CPI_HEADLINE_MOM",
            release_cluster="BLS_0830",
            market_description="CPI all-items month-over-month threshold market",
            settlement_source="BLS CPI release",
            settlement_source_url=bls_url,
            release_time_et="08:30",
            schedule_source_url=bls_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official BLS CPI release print timestamped 08:30 ET.",
            mispricing_hypothesis="Gasoline, airfare, and shelter nowcasts diverge from consensus threshold odds.",
            confounders="Base effects, seasonal-factor changes, and revisions.",
            **macro_common,
        ),
        _spec(
            canonical_ticker="MX02_CPI_CORE_MOM",
            release_cluster="BLS_0830",
            market_description="CPI core month-over-month threshold market",
            settlement_source="BLS CPI release",
            settlement_source_url=bls_url,
            release_time_et="08:30",
            schedule_source_url=bls_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official BLS core CPI print at release time.",
            mispricing_hypothesis="Market overweights headline swings and underweights shelter/services persistence.",
            confounders="OER lag, used-car swings, medical services noise.",
            **macro_common,
        ),
        _spec(
            canonical_ticker="MX03_CPI_HEADLINE_YOY",
            release_cluster="BLS_0830",
            market_description="CPI all-items year-over-year threshold market",
            settlement_source="BLS CPI release",
            settlement_source_url=bls_url,
            release_time_et="08:30",
            schedule_source_url=bls_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official BLS headline CPI YoY value.",
            mispricing_hypothesis="Monthly pulse is priced but base-effect path is mispriced.",
            confounders="YoY base effects can move opposite current monthly trend.",
            **macro_common,
        ),
        _spec(
            canonical_ticker="MX04_CPI_CORE_YOY",
            release_cluster="BLS_0830",
            market_description="CPI core year-over-year threshold market",
            settlement_source="BLS CPI release",
            settlement_source_url=bls_url,
            release_time_et="08:30",
            schedule_source_url=bls_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official BLS core CPI YoY value.",
            mispricing_hypothesis="Housing disinflation pace and sticky services are often misweighted.",
            confounders="Weight drift and revisions to prior month.",
            **macro_common,
        ),
        _spec(
            canonical_ticker="MX05_PPI_FINAL_DEMAND_MOM",
            release_cluster="BLS_0830",
            market_description="PPI final demand month-over-month threshold market",
            settlement_source="BLS PPI release",
            settlement_source_url=bls_url,
            release_time_et="08:30",
            schedule_source_url=bls_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official BLS PPI final demand MoM value.",
            mispricing_hypothesis="Commodity/freight pass-through lags are not fully reflected in odds.",
            confounders="Services trade margins create one-off spikes.",
            **macro_common,
        ),
        _spec(
            canonical_ticker="MX06_PPI_CORE_MOM",
            release_cluster="BLS_0830",
            market_description="PPI core month-over-month threshold market",
            settlement_source="BLS PPI release",
            settlement_source_url=bls_url,
            release_time_et="08:30",
            schedule_source_url=bls_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official BLS core PPI value.",
            mispricing_hypothesis="Headline pipeline shocks are misread as core trend.",
            confounders="Transport and trade services volatility.",
            **macro_common,
        ),
        _spec(
            canonical_ticker="MX07_NFP_CHANGE",
            release_cluster="BLS_0830",
            market_description="Nonfarm payrolls change threshold market",
            settlement_source="BLS Employment Situation",
            settlement_source_url=bls_url,
            release_time_et="08:30",
            schedule_source_url=bls_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official BLS nonfarm payroll change value.",
            mispricing_hypothesis="Claims, withholding, and weather effects imply threshold odds drift pre-release.",
            confounders="Birth-death model impact and benchmark revisions.",
            **macro_common,
        ),
        _spec(
            canonical_ticker="MX08_UNEMP_RATE",
            release_cluster="BLS_0830",
            market_description="Unemployment rate threshold market",
            settlement_source="BLS Employment Situation",
            settlement_source_url=bls_url,
            release_time_et="08:30",
            schedule_source_url=bls_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official BLS unemployment rate value.",
            mispricing_hypothesis="Household survey deterioration can be underpriced versus payroll focus.",
            confounders="Participation swings and household survey variance.",
            **macro_common,
        ),
        _spec(
            canonical_ticker="MX09_AHE_MOM",
            release_cluster="BLS_0830",
            market_description="Average hourly earnings month-over-month threshold market",
            settlement_source="BLS Employment Situation",
            settlement_source_url=bls_url,
            release_time_et="08:30",
            schedule_source_url=bls_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official BLS AHE MoM value.",
            mispricing_hypothesis="Composition effects often mistaken for true wage acceleration.",
            confounders="Bonus timing, hours mix, and sector rotation.",
            **macro_common,
        ),
        _spec(
            canonical_ticker="MX10_JOLTS_OPENINGS",
            release_cluster="BLS_1000",
            market_description="JOLTS job openings threshold market",
            settlement_source="BLS JOLTS release",
            settlement_source_url=bls_url,
            release_time_et="10:00",
            schedule_source_url=bls_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official BLS JOLTS openings value at 10:00 ET.",
            mispricing_hypothesis="Vacancy trend inflection reaches market odds late.",
            confounders="Revision profile and response-rate noise.",
            **macro_common,
        ),
        _spec(
            canonical_ticker="MX11_JOLTS_QUITS_RATE",
            release_cluster="BLS_1000",
            market_description="JOLTS quits rate threshold market",
            settlement_source="BLS JOLTS release",
            settlement_source_url=bls_url,
            release_time_et="10:00",
            schedule_source_url=bls_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official BLS JOLTS quits-rate value.",
            mispricing_hypothesis="Worker-confidence turns can lead payroll data and be underpriced.",
            confounders="Annual revisions and sector-composition shifts.",
            **macro_common,
        ),
        _spec(
            canonical_ticker="MX12_RETAIL_SALES_HEADLINE_MOM",
            release_cluster="CENSUS_0830",
            market_description="Headline retail sales month-over-month threshold market",
            settlement_source="Census retail sales release",
            settlement_source_url=census_url,
            release_time_et="08:30",
            schedule_source_url=census_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official Census advance retail sales MoM print.",
            mispricing_hypothesis="Gas and auto nominal distortions create threshold mispricing.",
            confounders="Price effects and revisions.",
            **macro_common,
        ),
        _spec(
            canonical_ticker="MX13_DURABLE_GOODS_ORDERS_MOM",
            release_cluster="CENSUS_0830",
            market_description="Durable goods orders month-over-month threshold market",
            settlement_source="Census durable goods release",
            settlement_source_url=census_url,
            release_time_et="08:30",
            schedule_source_url=census_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official Census durable goods MoM print.",
            mispricing_hypothesis="Transport/aircraft noise around thresholds is often under-hedged.",
            confounders="Aircraft orders dominate monthly variance.",
            **macro_common,
        ),
        _spec(
            canonical_ticker="MX14_HOUSING_STARTS_SAAR",
            release_cluster="CENSUS_0830",
            market_description="Housing starts SAAR threshold market",
            settlement_source="Census new residential construction",
            settlement_source_url=census_url,
            release_time_et="08:30",
            schedule_source_url=census_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official Census housing starts SAAR value.",
            mispricing_hypothesis="Mortgage-rate and weather effects can move starts more than odds imply.",
            confounders="Multifamily volatility and methodology updates.",
            **macro_common,
        ),
        _spec(
            canonical_ticker="MX15_BUILDING_PERMITS_SAAR",
            release_cluster="CENSUS_0830",
            market_description="Building permits SAAR threshold market",
            settlement_source="Census new residential construction",
            settlement_source_url=census_url,
            release_time_et="08:30",
            schedule_source_url=census_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official Census building permits SAAR value.",
            mispricing_hypothesis="Permit pipeline inflects before starts but is often underweighted.",
            confounders="Imputation and local-office timing differences.",
            **macro_common,
        ),
        _spec(
            canonical_ticker="MX16_NEW_HOME_SALES_SAAR",
            release_cluster="CENSUS_1000",
            market_description="New home sales SAAR threshold market",
            settlement_source="Census new home sales",
            settlement_source_url=census_url,
            release_time_et="10:00",
            schedule_source_url=census_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official Census new home sales SAAR value.",
            mispricing_hypothesis="Builder incentives can shift closings faster than consensus odds.",
            confounders="Cancellations and wide confidence intervals.",
            **macro_common,
        ),
        _spec(
            canonical_ticker="MX17_CORE_PCE_MOM",
            release_cluster="BEA_0830",
            market_description="Core PCE month-over-month threshold market",
            settlement_source="BEA Personal Income and Outlays",
            settlement_source_url=bea_url,
            release_time_et="08:30",
            schedule_source_url=bea_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official BEA core PCE MoM value.",
            mispricing_hypothesis="CPI-to-PCE mapping is treated too mechanically in market pricing.",
            confounders="Different BEA weights, residual categories, revisions.",
            **macro_common,
        ),
        _spec(
            canonical_ticker="MX18_PERSONAL_INCOME_MOM",
            release_cluster="BEA_0830",
            market_description="Personal income month-over-month threshold market",
            settlement_source="BEA Personal Income and Outlays",
            settlement_source_url=bea_url,
            release_time_et="08:30",
            schedule_source_url=bea_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official BEA personal income MoM value.",
            mispricing_hypothesis="Transfer/dividend/farm components are often under-modeled.",
            confounders="One-off policy transfer or dividend events.",
            **macro_common,
        ),
        _spec(
            canonical_ticker="MX19_GDP_ADVANCE_QOQ_ANN",
            release_cluster="BEA_0830",
            market_description="GDP advance annualized quarter-over-quarter threshold market",
            settlement_source="BEA GDP advance release",
            settlement_source_url=bea_url,
            release_time_et="08:30",
            schedule_source_url=bea_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official BEA GDP advance QoQ annualized value.",
            mispricing_hypothesis="Inventory and trade nowcast error creates threshold edge.",
            confounders="Advance print uses incomplete source data.",
            **macro_common,
        ),
        _spec(
            canonical_ticker="MX20_FOMC_TARGET_RANGE",
            release_cluster="FOMC_1400",
            market_description="FOMC target range decision threshold market",
            settlement_source="Federal Reserve FOMC statement",
            settlement_source_url=fed_url,
            release_time_et="14:00",
            schedule_source_url=fed_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle from 14:00 ET policy statement only, not 14:30 press conference.",
            mispricing_hypothesis="Statement-decision probabilities can diverge from final implied range pricing.",
            confounders="14:30 press conference can move quotes after settlement source is fixed.",
            entry_min_edge_net=0.015,
            entry_min_confidence=0.62,
            entry_min_evidence_count=4,
            entry_max_price_dollars=0.68,
            entry_max_spread_dollars=0.04,
            per_market_risk_cap_fraction_nav=0.0012,
            notes="Highest event risk in macro set; stricter edge/confidence gate.",
            niche="macro_release",
            execution_phase="phase1_live",
        ),
    ]


def _energy_specs() -> list[dict[str, Any]]:
    wpsr_url = "https://www.eia.gov/petroleum/supply/weekly/schedule.php"
    wngsr_url = "https://ir.eia.gov/ngs/schedule.html"
    gdfu_url = "https://www.eia.gov/petroleum/gasdiesel/schedule.php"
    hopu_url = "https://www.eia.gov/petroleum/heatingoilpropane/schedule.php"

    energy_common = {
        "niche": "weather_energy_transmission",
        "execution_phase": "phase1_live",
        "entry_min_edge_net": 0.010,
        "entry_min_confidence": 0.56,
        "entry_min_evidence_count": 3,
        "entry_max_price_dollars": 0.74,
        "entry_max_spread_dollars": 0.06,
        "per_market_risk_cap_fraction_nav": 0.0018,
        "notes": "EIA-settled energy release contract with NOAA/NWS signal layer.",
    }

    return [
        _spec(
            canonical_ticker="EN01_CRUDE_STOCKS_EXSPR",
            release_cluster="EIA_WPSR_1030_WED",
            market_description="WPSR U.S. crude stocks ex-SPR change threshold market",
            settlement_source="EIA Weekly Petroleum Status Report",
            settlement_source_url=wpsr_url,
            release_time_et="10:30",
            schedule_source_url=wpsr_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official WPSR table release for weekly crude stocks ex-SPR.",
            mispricing_hypothesis="Refinery runs, imports, and weather outages imply delta not reflected in odds.",
            confounders="Week-ending-Friday sampling and cargo-timing noise.",
            **energy_common,
        ),
        _spec(
            canonical_ticker="EN02_CUSHING_CRUDE_STOCKS",
            release_cluster="EIA_WPSR_1030_WED",
            market_description="WPSR Cushing crude stocks threshold market",
            settlement_source="EIA Weekly Petroleum Status Report",
            settlement_source_url=wpsr_url,
            release_time_et="10:30",
            schedule_source_url=wpsr_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official WPSR Cushing inventory table value.",
            mispricing_hypothesis="Pipeline-flow and spread dislocations are slow to update implied odds.",
            confounders="Operational pipeline moves can dominate fundamentals.",
            **energy_common,
        ),
        _spec(
            canonical_ticker="EN03_GASOLINE_STOCKS",
            release_cluster="EIA_WPSR_1030_WED",
            market_description="WPSR gasoline stocks threshold market",
            settlement_source="EIA Weekly Petroleum Status Report",
            settlement_source_url=wpsr_url,
            release_time_et="10:30",
            schedule_source_url=wpsr_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official WPSR motor gasoline stocks value.",
            mispricing_hypothesis="Yield + weather demand transmission misprices near-threshold outcomes.",
            confounders="Blending and seasonal fuel-spec transitions.",
            **energy_common,
        ),
        _spec(
            canonical_ticker="EN04_DISTILLATE_STOCKS",
            release_cluster="EIA_WPSR_1030_WED",
            market_description="WPSR distillate stocks threshold market",
            settlement_source="EIA Weekly Petroleum Status Report",
            settlement_source_url=wpsr_url,
            release_time_et="10:30",
            schedule_source_url=wpsr_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official WPSR distillate stocks value.",
            mispricing_hypothesis="Heating and freight demand turns can beat consensus pricing.",
            confounders="Export swings may dominate domestic weather.",
            **energy_common,
        ),
        _spec(
            canonical_ticker="EN05_JET_FUEL_STOCKS",
            release_cluster="EIA_WPSR_1030_WED",
            market_description="WPSR jet fuel stocks threshold market",
            settlement_source="EIA Weekly Petroleum Status Report",
            settlement_source_url=wpsr_url,
            release_time_et="10:30",
            schedule_source_url=wpsr_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official WPSR jet fuel inventory value.",
            mispricing_hypothesis="Travel-weather disruption linkage is underweighted in implied odds.",
            confounders="Airline schedule shocks are not trend demand.",
            **energy_common,
        ),
        _spec(
            canonical_ticker="EN06_PROPANE_PROPYLENE_STOCKS",
            release_cluster="EIA_WPSR_1030_WED",
            market_description="WPSR propane/propylene stocks threshold market",
            settlement_source="EIA Weekly Petroleum Status Report",
            settlement_source_url=wpsr_url,
            release_time_et="10:30",
            schedule_source_url=wpsr_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official WPSR propane and propylene stocks value.",
            mispricing_hypothesis="Cold/HDD and export pull tighten balances faster than market odds.",
            confounders="Petrochemical demand and Gulf logistics.",
            **energy_common,
        ),
        _spec(
            canonical_ticker="EN07_REFINERY_UTILIZATION",
            release_cluster="EIA_WPSR_1030_WED",
            market_description="WPSR refinery utilization threshold market",
            settlement_source="EIA Weekly Petroleum Status Report",
            settlement_source_url=wpsr_url,
            release_time_et="10:30",
            schedule_source_url=wpsr_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official WPSR refinery utilization percent value.",
            mispricing_hypothesis="Turnarounds and outage risk can move runs beyond priced range.",
            confounders="Operable-capacity denominator updates monthly.",
            **energy_common,
        ),
        _spec(
            canonical_ticker="EN08_CRUDE_INPUTS_TO_REFINERIES",
            release_cluster="EIA_WPSR_1030_WED",
            market_description="WPSR crude inputs to refineries threshold market",
            settlement_source="EIA Weekly Petroleum Status Report",
            settlement_source_url=wpsr_url,
            release_time_et="10:30",
            schedule_source_url=wpsr_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official WPSR crude inputs to refineries value.",
            mispricing_hypothesis="Run-rate changes can lead inventory consensus shifts.",
            confounders="Maintenance timing and unplanned outages.",
            **energy_common,
        ),
        _spec(
            canonical_ticker="EN09_CRUDE_IMPORTS",
            release_cluster="EIA_WPSR_1030_WED",
            market_description="WPSR crude imports threshold market",
            settlement_source="EIA Weekly Petroleum Status Report",
            settlement_source_url=wpsr_url,
            release_time_et="10:30",
            schedule_source_url=wpsr_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official WPSR crude imports weekly value.",
            mispricing_hypothesis="Tanker bunching effects are often underpriced pre-release.",
            confounders="Pure timing noise can dominate signal.",
            **energy_common,
        ),
        _spec(
            canonical_ticker="EN10_GASOLINE_PRODUCT_SUPPLIED",
            release_cluster="EIA_WPSR_1030_WED",
            market_description="WPSR gasoline product supplied threshold market",
            settlement_source="EIA Weekly Petroleum Status Report",
            settlement_source_url=wpsr_url,
            release_time_et="10:30",
            schedule_source_url=wpsr_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official WPSR gasoline product supplied value.",
            mispricing_hypothesis="Weather and holiday demand swings can be misread in implied odds.",
            confounders="Product supplied is demand proxy, not direct consumption.",
            **energy_common,
        ),
        _spec(
            canonical_ticker="EN11_LOWER48_WORKING_GAS_CHANGE",
            release_cluster="EIA_WNGSR_1030_THU",
            market_description="WNGSR Lower 48 working gas weekly change threshold market",
            settlement_source="EIA Weekly Natural Gas Storage Report",
            settlement_source_url=wngsr_url,
            release_time_et="10:30",
            schedule_source_url=wngsr_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official WNGSR Lower 48 weekly change value.",
            mispricing_hypothesis="HDD/CDD, LNG feedgas, and maintenance imply different storage delta.",
            confounders="Pipeline outages can dominate weather model expectations.",
            **energy_common,
        ),
        _spec(
            canonical_ticker="EN12_EAST_WORKING_GAS_CHANGE",
            release_cluster="EIA_WNGSR_1030_THU",
            market_description="WNGSR East region working gas change threshold market",
            settlement_source="EIA Weekly Natural Gas Storage Report",
            settlement_source_url=wngsr_url,
            release_time_et="10:30",
            schedule_source_url=wngsr_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official WNGSR East region storage change value.",
            mispricing_hypothesis="Northeast weather and basis shocks reach odds with lag.",
            confounders="Regional pipe constraints.",
            **energy_common,
        ),
        _spec(
            canonical_ticker="EN13_MIDWEST_WORKING_GAS_CHANGE",
            release_cluster="EIA_WNGSR_1030_THU",
            market_description="WNGSR Midwest region working gas change threshold market",
            settlement_source="EIA Weekly Natural Gas Storage Report",
            settlement_source_url=wngsr_url,
            release_time_et="10:30",
            schedule_source_url=wngsr_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official WNGSR Midwest region storage change value.",
            mispricing_hypothesis="Midwest HDD shocks can be underweighted into release.",
            confounders="Storage field operations and outage events.",
            **energy_common,
        ),
        _spec(
            canonical_ticker="EN14_SOUTHCENTRAL_WORKING_GAS_CHANGE",
            release_cluster="EIA_WNGSR_1030_THU",
            market_description="WNGSR South Central region working gas change threshold market",
            settlement_source="EIA Weekly Natural Gas Storage Report",
            settlement_source_url=wngsr_url,
            release_time_et="10:30",
            schedule_source_url=wngsr_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official WNGSR South Central storage change value.",
            mispricing_hypothesis="Gulf weather and LNG pull can outpace implied probabilities.",
            confounders="Salt-cavern volatility and operational shifts.",
            **energy_common,
        ),
        _spec(
            canonical_ticker="EN15_PACIFIC_WORKING_GAS_CHANGE",
            release_cluster="EIA_WNGSR_1030_THU",
            market_description="WNGSR Pacific region working gas change threshold market",
            settlement_source="EIA Weekly Natural Gas Storage Report",
            settlement_source_url=wngsr_url,
            release_time_et="10:30",
            schedule_source_url=wngsr_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official WNGSR Pacific region storage change value.",
            mispricing_hypothesis="West weather and power burn shifts can surprise consensus odds.",
            confounders="Hydro substitution and transmission constraints.",
            **energy_common,
        ),
        _spec(
            canonical_ticker="EN16_US_REG_GAS_PRICE",
            release_cluster="EIA_GDFU_1000_TUE",
            market_description="GDFU U.S. regular gasoline retail price threshold market",
            settlement_source="EIA Gasoline and Diesel Fuel Update",
            settlement_source_url=gdfu_url,
            release_time_et="10:00",
            schedule_source_url=gdfu_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official Tuesday GDFU U.S. regular gasoline price.",
            mispricing_hypothesis="Crack spread and local supply pass-through speed misprices threshold odds.",
            confounders="Monday snapshot with taxes included.",
            **energy_common,
        ),
        _spec(
            canonical_ticker="EN17_US_DIESEL_PRICE",
            release_cluster="EIA_GDFU_1000_TUE",
            market_description="GDFU U.S. diesel retail price threshold market",
            settlement_source="EIA Gasoline and Diesel Fuel Update",
            settlement_source_url=gdfu_url,
            release_time_et="10:00",
            schedule_source_url=gdfu_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official Tuesday GDFU U.S. on-highway diesel price.",
            mispricing_hypothesis="Freight demand and distillate crack shifts pass through unevenly.",
            confounders="Monday-only survey and tax-inclusive pricing.",
            **energy_common,
        ),
        _spec(
            canonical_ticker="EN18_US_RES_HEATING_OIL_PRICE",
            release_cluster="EIA_HOPU_1300_WED",
            market_description="HOPU U.S. residential heating oil price threshold market",
            settlement_source="EIA Heating Oil and Propane Update",
            settlement_source_url=hopu_url,
            release_time_et="13:00",
            schedule_source_url=hopu_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official HOPU residential heating-oil price (Oct-Mar season).",
            mispricing_hypothesis="Cold-shot demand and distillate cracks can move faster than survey expectations.",
            confounders="Seasonal cadence and one-week revision window.",
            **energy_common,
        ),
        _spec(
            canonical_ticker="EN19_US_RES_PROPANE_PRICE",
            release_cluster="EIA_HOPU_1300_WED",
            market_description="HOPU U.S. residential propane price threshold market",
            settlement_source="EIA Heating Oil and Propane Update",
            settlement_source_url=hopu_url,
            release_time_et="13:00",
            schedule_source_url=hopu_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official HOPU U.S. residential propane price (Oct-Mar season).",
            mispricing_hypothesis="Storage/export stress can appear in residential prints with lag mispricing.",
            confounders="Seasonal-only reporting and revision window.",
            **energy_common,
        ),
        _spec(
            canonical_ticker="EN20_MIDWEST_RES_PROPANE_PRICE",
            release_cluster="EIA_HOPU_1300_WED",
            market_description="HOPU Midwest residential propane price threshold market",
            settlement_source="EIA Heating Oil and Propane Update",
            settlement_source_url=hopu_url,
            release_time_et="13:00",
            schedule_source_url=hopu_url,
            schedule_needs_nightly_poll=True,
            schedule_holiday_shift_risk=True,
            source_timestamp_rule="Settle on first official HOPU Midwest (PADD 2) residential propane price (Oct-Mar season).",
            mispricing_hypothesis="Midwest cold shocks and logistics can decouple regional and national pricing.",
            confounders="Regional logistics and seasonal-only cadence.",
            **energy_common,
        ),
    ]


def build_canonical_specs() -> list[dict[str, Any]]:
    specs = _macro_specs() + _energy_specs()
    specs.sort(key=lambda row: row["canonical_ticker"])
    return specs


def build_contract_mapping_rows(
    specs: list[dict[str, Any]],
    existing_rows: list[dict[str, str]] | None = None,
) -> list[dict[str, Any]]:
    existing_index = {
        str(row.get("canonical_ticker") or "").strip(): row
        for row in (existing_rows or [])
        if str(row.get("canonical_ticker") or "").strip()
    }

    rows: list[dict[str, Any]] = []
    for spec in specs:
        row = {
            "canonical_ticker": spec["canonical_ticker"],
            "niche": spec["niche"],
            "execution_phase": spec["execution_phase"],
            "market_description": spec["market_description"],
            "settlement_source": spec["settlement_source"],
            "settlement_source_url": spec["settlement_source_url"],
            "release_time_et": spec["release_time_et"],
            "schedule_source_url": spec["schedule_source_url"],
            "schedule_needs_nightly_poll": str(bool(spec["schedule_needs_nightly_poll"])).lower(),
            "schedule_holiday_shift_risk": str(bool(spec["schedule_holiday_shift_risk"])).lower(),
            "source_timestamp_rule": spec["source_timestamp_rule"],
            "mispricing_hypothesis": spec["mispricing_hypothesis"],
            "confounders": spec["confounders"],
            "mapping_status": "unmapped",
            "live_event_ticker": "",
            "live_market_ticker": "",
            "mapping_confidence": "",
            "mapping_notes": "",
            "last_mapped_at": "",
        }
        previous = existing_index.get(spec["canonical_ticker"])
        if previous is not None:
            for field in EDITABLE_MAPPING_FIELDS:
                value = str(previous.get(field) or "")
                if value:
                    row[field] = value
        rows.append(row)
    return rows


def build_threshold_rows(specs: list[dict[str, Any]]) -> list[dict[str, Any]]:
    rows: list[dict[str, Any]] = []
    for spec in specs:
        rows.append(
            {
                "canonical_ticker": spec["canonical_ticker"],
                "niche": spec["niche"],
                "execution_phase": spec["execution_phase"],
                "release_cluster": spec["release_cluster"],
                "entry_min_edge_net": round(float(spec["entry_min_edge_net"]), 6),
                "entry_min_confidence": round(float(spec["entry_min_confidence"]), 6),
                "entry_min_evidence_count": int(spec["entry_min_evidence_count"]),
                "entry_max_price_dollars": round(float(spec["entry_max_price_dollars"]), 6),
                "entry_max_spread_dollars": round(float(spec["entry_max_spread_dollars"]), 6),
                "per_market_risk_cap_fraction_nav": round(float(spec["per_market_risk_cap_fraction_nav"]), 6),
                "release_cluster_risk_cap_fraction_nav": 0.0035,
                "same_day_correlated_risk_cap_fraction_nav": 0.0075,
                "daily_soft_stop_fraction_nav": 0.0075,
                "daily_hard_stop_fraction_nav": 0.0125,
                "drawdown_soft_cap_fraction_nav": 0.10,
                "drawdown_hard_kill_fraction_nav": 0.12,
                "degrade_to_paper_after_stopouts": 2,
                "stopout_window_sessions": 5,
                "target_outperformance_vs_spx_points_min": 8,
                "target_outperformance_vs_spx_points_max": 12,
                "notes": spec["notes"],
            }
        )
    return rows


def run_canonical_universe(
    *,
    output_dir: str = "data/research",
    now: datetime | None = None,
) -> dict[str, Any]:
    captured_at = now or datetime.now(timezone.utc)
    out_dir = Path(output_dir)
    out_dir.mkdir(parents=True, exist_ok=True)

    mapping_path = out_dir / "canonical_contract_mapping.csv"
    threshold_path = out_dir / "canonical_threshold_library.csv"

    specs = build_canonical_specs()
    existing_mapping_rows = _read_csv_rows(mapping_path)
    mapping_rows = build_contract_mapping_rows(specs=specs, existing_rows=existing_mapping_rows)
    threshold_rows = build_threshold_rows(specs)

    _write_csv(mapping_path, MAPPING_FIELDNAMES, mapping_rows)
    _write_csv(threshold_path, THRESHOLD_FIELDNAMES, threshold_rows)

    stamp = captured_at.astimezone().strftime("%Y%m%d_%H%M%S")
    summary_path = out_dir / f"canonical_universe_summary_{stamp}.json"

    summary = {
        "captured_at": captured_at.isoformat(),
        "status": "ready",
        "output_dir": str(out_dir),
        "canonical_ticker_count": len(specs),
        "macro_release_count": sum(1 for row in specs if row["niche"] == "macro_release"),
        "weather_energy_count": sum(1 for row in specs if row["niche"] == "weather_energy_transmission"),
        "schedule_poll_required_count": sum(1 for row in specs if row["schedule_needs_nightly_poll"]),
        "mapping_unmapped_count": sum(1 for row in mapping_rows if row["mapping_status"] != "mapped"),
        "mapping_csv": str(mapping_path),
        "threshold_csv": str(threshold_path),
    }
    summary_path.write_text(json.dumps(summary, indent=2), encoding="utf-8")
    summary["output_file"] = str(summary_path)
    return summary
