from __future__ import annotations

from dataclasses import dataclass

from betbot.runtime.event_types import (
    PHASE_APPROVAL_WAITING,
    PHASE_CANDIDATES_SCORED,
    PHASE_CYCLE_FAILED,
    PHASE_CYCLE_FINISHED,
    PHASE_CYCLE_STARTED,
    PHASE_NEWS_ENRICHING,
    PHASE_ORDER_CANCELED,
    PHASE_ORDER_FILLED,
    PHASE_ORDER_PARTIALLY_FILLED,
    PHASE_ORDER_RESTING,
    PHASE_ORDER_SUBMITTED,
    PHASE_POLICY_CHECKED,
    PHASE_POSITION_OPEN,
    PHASE_POSITION_SETTLED,
    PHASE_SNAPSHOTS_NORMALIZED,
    PHASE_SOURCES_FETCHING,
    PHASE_SOURCES_PARTIAL,
    PHASE_SOURCES_READY,
    PHASE_TICKET_BLOCKED,
    PHASE_TICKET_READY,
)

_ALLOWED_TRANSITIONS: dict[str, tuple[str, ...]] = {
    PHASE_CYCLE_STARTED: (PHASE_SOURCES_FETCHING, PHASE_CYCLE_FAILED),
    PHASE_SOURCES_FETCHING: (PHASE_SOURCES_PARTIAL, PHASE_SOURCES_READY, PHASE_CYCLE_FAILED),
    PHASE_SOURCES_PARTIAL: (PHASE_SOURCES_READY, PHASE_CYCLE_FAILED),
    PHASE_SOURCES_READY: (PHASE_NEWS_ENRICHING, PHASE_CYCLE_FAILED),
    PHASE_NEWS_ENRICHING: (PHASE_SNAPSHOTS_NORMALIZED, PHASE_CYCLE_FAILED),
    PHASE_SNAPSHOTS_NORMALIZED: (PHASE_CANDIDATES_SCORED, PHASE_CYCLE_FAILED),
    PHASE_CANDIDATES_SCORED: (PHASE_POLICY_CHECKED, PHASE_CYCLE_FAILED),
    PHASE_POLICY_CHECKED: (PHASE_TICKET_READY, PHASE_TICKET_BLOCKED, PHASE_CYCLE_FAILED),
    PHASE_TICKET_READY: (PHASE_APPROVAL_WAITING, PHASE_ORDER_SUBMITTED, PHASE_CYCLE_FINISHED, PHASE_CYCLE_FAILED),
    PHASE_TICKET_BLOCKED: (PHASE_CYCLE_FINISHED, PHASE_CYCLE_FAILED),
    PHASE_APPROVAL_WAITING: (PHASE_ORDER_SUBMITTED, PHASE_CYCLE_FINISHED, PHASE_CYCLE_FAILED),
    PHASE_ORDER_SUBMITTED: (
        PHASE_ORDER_RESTING,
        PHASE_ORDER_PARTIALLY_FILLED,
        PHASE_ORDER_FILLED,
        PHASE_ORDER_CANCELED,
        PHASE_CYCLE_FAILED,
    ),
    PHASE_ORDER_RESTING: (
        PHASE_ORDER_PARTIALLY_FILLED,
        PHASE_ORDER_FILLED,
        PHASE_ORDER_CANCELED,
        PHASE_CYCLE_FAILED,
    ),
    PHASE_ORDER_PARTIALLY_FILLED: (
        PHASE_ORDER_FILLED,
        PHASE_ORDER_CANCELED,
        PHASE_POSITION_OPEN,
        PHASE_CYCLE_FAILED,
    ),
    PHASE_ORDER_FILLED: (PHASE_POSITION_OPEN, PHASE_POSITION_SETTLED, PHASE_CYCLE_FINISHED, PHASE_CYCLE_FAILED),
    PHASE_ORDER_CANCELED: (PHASE_CYCLE_FINISHED, PHASE_CYCLE_FAILED),
    PHASE_POSITION_OPEN: (PHASE_POSITION_SETTLED, PHASE_CYCLE_FINISHED, PHASE_CYCLE_FAILED),
    PHASE_POSITION_SETTLED: (PHASE_CYCLE_FINISHED, PHASE_CYCLE_FAILED),
    PHASE_CYCLE_FINISHED: (),
    PHASE_CYCLE_FAILED: (),
}


@dataclass
class RuntimeStateMachine:
    current_phase: str = PHASE_CYCLE_STARTED

    def transition(self, next_phase: str) -> None:
        allowed = _ALLOWED_TRANSITIONS.get(self.current_phase, ())
        if next_phase not in allowed:
            raise ValueError(
                f"Invalid runtime transition from {self.current_phase!r} to {next_phase!r}; "
                f"allowed={list(allowed)}"
            )
        self.current_phase = next_phase
